name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REACT_APP_AUTH_API_URL: ${{ secrets.REACT_APP_AUTH_API_URL }}
  REACT_APP_COLLECTIONS_API_URL: ${{ secrets.REACT_APP_COLLECTIONS_API_URL }}
  REACT_APP_STORAGE_JWT_KEY: ${{ secrets.REACT_APP_STORAGE_JWT_KEY }}
  REACT_APP_WEATHER_API_URL: ${{ secrets.REACT_APP_WEATHER_API_URL }}

jobs:
  checkout:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        
    - name: Save artifacts for next job
      uses: actions/upload-artifact@v2
      with:
        name: base
        path: ./

  install:
  
    needs: checkout

    runs-on: ubuntu-latest
  
    steps:
    - name: Get artifacts from last job
      uses: actions/download-artifact@v2
      with:
        name: base
    
    - name: Install dependencies
      run: npm ci
      
    - name: Set artifacts from last job
      uses: actions/download-artifact@v2
      with:
        name: app
        path: ./

  test:
  
    needs: install

    runs-on: ubuntu-latest
    
    steps:
    - name: Get artifacts from last job
      uses: actions/download-artifact@v2
      with:
        name: app
        
    - name: Run the tests
      run: npm test -- --coverage
      
    - name: Coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build:
  
    needs: install

    runs-on: ubuntu-latest
    
    steps:
    - name: Get artifacts from last job
      uses: actions/download-artifact@v2
      with:
        name: app
        
    - name: Build
      run: npm run build
      
    - name: Save build directory
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: /build
  
  deploy:
  
    needs: [test, build]
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Get build directory
      uses: actions/download-artifact@v2
      with:
        name: build
        
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=build --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
