name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REACT_APP_AUTH_API_URL: ${{ secrets.REACT_APP_AUTH_API_URL }}
  REACT_APP_COLLECTIONS_API_URL: ${{ secrets.REACT_APP_COLLECTIONS_API_URL }}
  REACT_APP_STORAGE_JWT_KEY: ${{ secrets.REACT_APP_STORAGE_JWT_KEY }}
  REACT_APP_WEATHER_API_URL: ${{ secrets.REACT_APP_WEATHER_API_URL }}

jobs:
  checkout:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

  install:
  
    needs: checkout

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm ci

    - name: Run the tests
      run: npm test -- --coverage
      
    - name: Coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Build
      run: npm run build
      
    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=build --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
